// Generated by scripts/update-tokens.py from
// https://github.com/Infomaniak/android-design-system (main). Do not edit by hand.

package com.infomaniak.dstokeninfo

/**
 * Resolved dimension values of the Infomaniak design system tokens, keyed by the
 * `EsdsTheme` accessor they are reached through (`icon`, `spacing`, `radius`).
 */
internal object EsdsTokenValues {

    val categories: Map<String, Map<String, String>> = mapOf(
        "icon" to mapOf(
            "sizeXs" to "16dp",
            "sizeMd" to "24dp",
            "sizeLg" to "32dp",
            "sizeSm" to "20dp",
            "sizeXl" to "40dp",
        ),
        "spacing" to mapOf(
            "none" to "0dp",
            "twoXs" to "2dp",
            "xs" to "4dp",
            "sm" to "6dp",
            "md" to "8dp",
            "lg" to "12dp",
            "xl" to "16dp",
            "twoXl" to "20dp",
            "threeXl" to "24dp",
            "fourXl" to "32dp",
            "fiveXl" to "40dp",
            "sixXl" to "48dp",
            "sevenXl" to "64dp",
            "eightXl" to "100dp",
        ),
        "radius" to mapOf(
            "none" to "0dp",
            "xs" to "2dp",
            "sm" to "4dp",
            "md" to "6dp",
            "lg" to "8dp",
            "xl" to "12dp",
            "twoXl" to "16dp",
            "threeXl" to "24dp",
            "fourXl" to "32dp",
            "full" to "full",
        ),
    )

    val knownCategories: Set<String> = categories.keys

    fun valueOf(category: String, token: String): String? = categories[category]?.get(token)
}
