#!/usr/bin/env python3
"""Regenerate EsdsTokenValues.kt from the Infomaniak Android design system.

The plugin cannot resolve `EsdsTheme.icon.sizeSm` at edit time (the values live behind
a Compose CompositionLocal), so the values are baked into the plugin instead. They are
not typed by hand: this script reads the *default theme* of the design system and
follows the token indirection all the way down to the primitive literals.

    DefaultIconTokens.sizeSm -> IntermediateDefault.IconSizeSm -> Scale20 -> 20.dp

Every app theme (Mail, kDrive, kChat, ...) currently maps these dimension tokens to the
exact same primitives, so the default theme is a faithful source for all of them.

Usage:
    python3 scripts/update-tokens.py [--ref main]
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys

REPO = "Infomaniak/android-design-system"
RAW = "https://raw.githubusercontent.com/{repo}/{ref}/{path}"

FOUNDATION = "Foundation/src/main/kotlin/com/infomaniak/designsystem/core"
PRIMITIVES = "PrimitiveTokens/src/main/kotlin/com/infomaniak/designsystem/primitivetokens"

OUTPUT = "src/main/kotlin/com/infomaniak/dstokeninfo/EsdsTokenValues.kt"

# EsdsTheme accessor -> file declaring the default mapping for that accessor.
CATEGORIES = {
    "icon": f"{FOUNDATION}/defaultvalues/DefaultIconTokens.kt",
    "spacing": f"{FOUNDATION}/defaultvalues/DefaultSpacingTokens.kt",
    "radius": f"{FOUNDATION}/defaultvalues/DefaultRadiusTokens.kt",
}

PRIMITIVE_FILES = [
    f"{PRIMITIVES}/ScalePrimitiveTokens.kt",
    f"{PRIMITIVES}/SpacingPrimitiveTokens.kt",
    f"{PRIMITIVES}/RadiusPrimitiveTokens.kt",
]

INTERMEDIATE = f"{FOUNDATION}/defaultvalues/internal/IntermediateDefault.kt"

VAL_RE = re.compile(r"^\s*val\s+(\w+)\s*:\s*\w+\s*=\s*(.+?)\s*$", re.MULTILINE)
ASSIGN_RE = re.compile(r"^\s*(\w+)\s*=\s*IntermediateDefault\.(\w+)\s*,\s*$", re.MULTILINE)


def fetch(path: str, ref: str) -> str:
    # `curl` is used instead of urllib so the script keeps working behind the corporate
    # TLS-inspecting proxy, whose root CA lives in the system trust store only.
    url = RAW.format(repo=REPO, ref=ref, path=path)
    result = subprocess.run(
        ["curl", "--silent", "--show-error", "--fail", "--location", url],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise SystemExit(f"Failed to fetch {url}: {result.stderr.strip()}")
    return result.stdout


def format_number(raw: str) -> str:
    """`20` -> `20`, `1.5` -> `1.5`, `4.0` -> `4`."""
    value = float(raw)
    return str(int(value)) if value.is_integer() else str(value)


def render_primitive(expression: str) -> str:
    """Turn a primitive declaration's right-hand side into something human readable."""
    expression = expression.strip()

    dp = re.fullmatch(r"([\d.]+)\.dp", expression)
    if dp:
        return f"{format_number(dp.group(1))}dp"

    rounded = re.fullmatch(r"RoundedCornerShape\(([\d.]+)\.dp\)", expression)
    if rounded:
        return f"{format_number(rounded.group(1))}dp"

    if expression == "RectangleShape":
        return "0dp"
    if expression == "CircleShape":
        return "full"

    return expression


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ref", default="main", help="Git ref of the design system to read")
    args = parser.parse_args()

    primitives: dict[str, str] = {}
    for path in PRIMITIVE_FILES:
        for name, expression in VAL_RE.findall(fetch(path, args.ref)):
            primitives[name] = render_primitive(expression)

    intermediate: dict[str, str] = {}
    for name, expression in VAL_RE.findall(fetch(INTERMEDIATE, args.ref)):
        intermediate[name] = expression.strip()

    categories: dict[str, dict[str, str]] = {}
    for category, path in CATEGORIES.items():
        tokens: dict[str, str] = {}
        for prop, intermediate_name in ASSIGN_RE.findall(fetch(path, args.ref)):
            primitive = intermediate.get(intermediate_name)
            if primitive is None:
                raise SystemExit(f"Unknown IntermediateDefault.{intermediate_name}")
            value = primitives.get(primitive)
            if value is None:
                raise SystemExit(f"Unknown primitive {primitive} for {category}.{prop}")
            tokens[prop] = value
        if not tokens:
            raise SystemExit(f"No tokens parsed for category '{category}' from {path}")
        categories[category] = tokens

    lines = [
        "// Generated by scripts/update-tokens.py from",
        f"// https://github.com/{REPO} ({args.ref}). Do not edit by hand.",
        "",
        "package com.infomaniak.dstokeninfo",
        "",
        "/**",
        " * Resolved dimension values of the Infomaniak design system tokens, keyed by the",
        " * `EsdsTheme` accessor they are reached through (`icon`, `spacing`, `radius`).",
        " */",
        "internal object EsdsTokenValues {",
        "",
        "    val categories: Map<String, Map<String, String>> = mapOf(",
    ]
    for category, tokens in categories.items():
        lines.append(f'        "{category}" to mapOf(')
        for prop, value in tokens.items():
            lines.append(f'            "{prop}" to "{value}",')
        lines.append("        ),")
    lines += [
        "    )",
        "",
        "    val knownCategories: Set<String> = categories.keys",
        "",
        "    fun valueOf(category: String, token: String): String? = categories[category]?.get(token)",
        "}",
        "",
    ]

    with open(OUTPUT, "w", encoding="utf-8") as output:
        output.write("\n".join(lines))

    total = sum(len(tokens) for tokens in categories.values())
    print(f"Wrote {OUTPUT} ({total} tokens across {len(categories)} categories)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
